### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by daonb** [hasadna/knesset-data#73]
```bash
$ pip install knesset-data
Downloading/unpacking knesset-data
  Using download cache from /home/...knesset-data-1.1.0.tar.gz
  Running setup.py (path:/tmp/pip-build-XvqxT3/knesset-data/setup.py) egg_info for package knesset-data 
...
Downloading/unpacking pyslet (from knesset-data)
  Downloading pyslet-0.6.20160201.tar.gz (2.8MB): 2.8MB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/daonb/yeda/Open-Knesset/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/daonb/yeda/Open-Knesset/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/daonb/yeda/Open-Knesset/env/local/lib/python2.7/site-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/home/daonb/yeda/Open-Knesset/env/local/lib/python2.7/site-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/home/daonb/yeda/Open-Knesset/env/local/lib/python2.7/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/home/daonb/yeda/Open-Knesset/env/local/lib/python2.7/site-packages/pip/util.py", line 644, in unpack_file
    untar_file(filename, location)
  File "/home/daonb/yeda/Open-Knesset/env/local/lib/python2.7/site-packages/pip/util.py", line 575, in untar_file
    path = os.path.join(location, fn)
  File "/home/daonb/yeda/Open-Knesset/env/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 36: ordinal not in range(128)

Storing debug log for failure in /home/daonb/.pip/pip.log
```

**Comment by OriHoch** [comment]
@daonb - try to upgrade your pip:

$ pip install --upgrade pip

**Comment by daonb** [comment]
Thanks!
